### ISSUE TITLE
404 Not found 페이지 구현

### ISSUE THREAD

**Issue by RyumForCode** [samjan29/sherlock-holmes#2]
+ 404 Not found Error 페이지 App.py 라우트 구현
+ 404 Not found Error CSS 작성

**Comment by RyumForCode** [comment]
404 Not found Error CSS 작성은 제가 맡겠습니다.

**Comment by Joohyein** [comment]
404 Not found Error 페이지 App.py 라우트 구현 해보겠습니다.

**Comment by RyumForCode** [comment]
```py

from flask import render_template
@app.errorhandler(404)
def page_not_found(error):
    return render_template('404.html')
```
app.py 404 Not found Error 페이지 예시 코드 스니펫

**Comment by Joohyein** [comment]
404 Not found Error 페이지 App.py 라우트 구현 완료했습니다.

**Comment by RyumForCode** [comment]
+ 404 Not found Error 페이지 CSS 정리, HTML 버튼 추가
+ HTML 파일 CSS 링크 디렉토리 상대경로로 수정
