### ISSUE TITLE
fix : 🔴 중복 렌더링 해결

### ISSUE THREAD

**Issue by samjan29** [samjan29/sherlock-holmes#9]
같은 이름의 이미지 파일이 저장되는 이슈 해결
불러올 때도 문제가 됨

**Comment by RyumForCode** [comment]
Add issue - fix: 문제 풀기 페이지 내에서 HTML 개발자 도구로 확인하면 이미지 이름으로 답을 유추할 수 있는 문제

**Comment by samjan29** [comment]
해결 예에
